---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Enable Nginx service
  systemd:
    name: nginx
    enabled: yes

# - name: Copy Nginx configuration file
#   copy:
#     src: templates/nginx.conf.j2
#     dest: /etc/nginx/nginx.conf

- name: Reload Nginx
  systemd:
    name: nginx
    state: restarted
