---
- name: Configure Nginx
  remote_user: ubuntu
  become: true
  hosts: all
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: latest

  - name: Create index.html file with IP address
    copy:
      dest: /var/www/html/index.nginx-debian.html 
      content: |
        <!DOCTYPE html>
        <html>
        <head>
        <title>{{ nginx_ip }}</title>
        <style>
            body {
                width: 35em;
                margin: 0 auto;
                font-family: Tahoma, Verdana, Arial, sans-serif;
            }
        </style>
        </head>
        <body>
        <h1>Welcome to nginx! This is displaying on EC2 with IP {{ nginx_ip }}</h1>
        <p>If you see this page, the nginx web server is successfully installed and
        working. Further configuration is required.</p>

        <p>For online documentation and support please refer to
        <a href="http://nginx.org/">nginx.org</a>.<br/>
        Commercial support is available at
        <a href="http://nginx.com/">nginx.com</a>.</p>

        <p><em>Thank you for using nginx.</em></p>
        </body>
        </html>

  - name: Reload Nginx
    service:
      name: nginx
      state: restarted
