---
- name: Install and configure HAProxy
  remote_user: ubuntu
  become: true
  hosts: all
  vars:
    haproxy_config_file: /etc/haproxy/haproxy.cfg
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration file
      template:
        src: ../templates/haproxy.cfg.j2
        dest: "{{ haproxy_config_file }}"
      vars:
        web_server_ips: "{{ extra_vars.web_server_ips }}"

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
